const express = require("express");
const usuarioRoutes = require("./usuarioRoutes");
const tokenRoutes = require("./tokensRoutes");
const authRoutes = require("./authRoutes");
const setorRouter = require("./setorRoutes");
const cleinteRoutes = require("./clienteRoutes");
const relatorioRoutes = require("./relatorioRoutes");
const receberRoutes = require("./contasAreceberRoutes");
const pagarRoutes = require("./contasApagarRoutes");
const pagamentoRoutes = require("./pagamentoRoutes");
const categoriaRoutes = require("./categoriaRoutes");
const petRoutes = require("./petRoutes");
const racaRoutes = require("./racaRoutes");
const vacinaRoutes = require("./vacinaRoutes");
const parceirosRoutes = require("./parceirosRoutes");
const tipoRoutes = require("./tipoRoutes");
const exameFisicoRoutes = require("./anamnese/exameFisicoRoutes");
const manejoRoutes = require("./anamnese/manejoRoutes");
const sistemaCardioRoutes = require("./anamnese/sistemaCardioRoutes");
const sistemaGastroRoutes = require("./anamnese/sistemaGastroRoutes");
const sistemaLocomotorRoutes = require("./anamnese/sistemaLocomotorRoutes");
const sistemaNeuroLogicoRoutes = require("./anamnese/sistemaNeuroLogicoRoutes");
const sistemaTegumentarRoutes = require("./anamnese/sistemaTegumentarRoutes");
const sistemaUrinarioRoutes = require("./anamnese/sistemaUrinarioRoutes");
const candidatoRoutes = require("./candidatoRoutes");
const demandasRoutes = require("./demandasRoutes");
const SolicitanteRoutes = require("./SolicitanteRoutes");
const OperacaoRoutes = require("./operacoesRoutes");
const router = express.Router();

router.use("/", authRoutes);
router.use("/", usuarioRoutes);
router.use("/", tokenRoutes);
router.use("/", setorRouter);
router.use("/", cleinteRoutes);
router.use("/", relatorioRoutes);
router.use("/", pagarRoutes);
router.use("/", receberRoutes);
router.use("/", pagamentoRoutes);
router.use("/", categoriaRoutes);
router.use("/", petRoutes);
router.use("/", racaRoutes);
router.use("/", vacinaRoutes);
router.use("/", parceirosRoutes);
router.use("/", demandasRoutes);
router.use("/", SolicitanteRoutes);
router.use("/", candidatoRoutes);
router.use("/", tipoRoutes);
router.use("/", exameFisicoRoutes);
router.use("/", OperacaoRoutes);
router.use("/", manejoRoutes);
router.use("/", sistemaCardioRoutes);
router.use("/", sistemaGastroRoutes);
router.use("/", sistemaLocomotorRoutes);
router.use("/", sistemaNeuroLogicoRoutes);
router.use("/", sistemaTegumentarRoutes);
router.use("/", sistemaUrinarioRoutes);

module.exports = router;
